/**
 * tools-data.js — My AI Tools Finder
 * Auto-generated. Do not edit manually.
 */
window.MYAI_AFF_MAP = {
  "15five":                "https://15five.com",
  "15five ai":             "https://15five.com",
  "6sense":                "https://6sense.com",
  "6sense ai":             "https://6sense.com",
  "abridge":               "https://abridge.com",
  "abridge ai":            "https://abridge.com",
  "activecampaign":        "https://activecampaign.com",
  "activecampaign ai":     "https://activecampaign.com",
  "activepieces":          "https://activepieces.com",
  "ada":                   "https://ada.cx",
  "ada ai":                "https://ada.cx",
  "ada health":            "https://ada.com",
  "adcreative.ai":         "https://adcreative.ai",
  "adobe express":         "https://adobe.com/express",
  "adobe express ai":      "https://adobe.com/express",
  "adobe firefly":         "https://firefly.adobe.com",
  "adobe podcast":         "https://podcast.adobe.com",
  "ahrefs":                "https://ahrefs.com",
  "ai writer":             "https://ai-writer.com",
  "airtable":              "https://airtable.com",
  "airtable ai":           "https://airtable.com",
  "akiflow":               "https://akiflow.com",
  "akkio":                 "https://akkio.com",
  "albato":                "https://albato.com",
  "alli":                  "https://alliai.com",
  "alli ai":               "https://alliai.com",
  "alphasense":            "https://alpha-sense.com",
  "amazon q":              "https://aws.amazon.com/q",
  "amie":                  "https://amie.so",
  "amplemarket":           "https://amplemarket.com",
  "amplemarket ai":        "https://amplemarket.com",
  "amplitude":             "https://amplitude.com",
  "amplitude ai":          "https://amplitude.com",
  "anytype":               "https://anytype.io",
  "anytype ai":            "https://anytype.io",
  "anyword":               "https://anyword.com",
  "apollo.io":             "https://apollo.io",
  "arcads":                "https://arcads.ai",
  "arcads ai":             "https://arcads.ai",
  "artbreeder":            "https://artbreeder.com",
  "article forge":         "https://articleforge.com",
  "asana intelligence":    "https://asana.com/product/ai",
  "ashby hr":              "https://ashbyhq.com",
  "askcodi":               "https://askcodi.com",
  "assemblyai":            "https://assemblyai.com",
  "attentive":             "https://attentive.com",
  "attentive ai":          "https://attentive.com",
  "audo studio":           "https://audo.ai",
  "auphonic":              "https://auphonic.com",
  "authoredup":            "https://authoredup.com",
  "avoma":                 "https://avoma.com",
  "avoma ai":              "https://avoma.com",
  "aws codewhisperer":     "https://aws.amazon.com/codewhisperer",
  "bamboohr":              "https://bamboohr.com",
  "bamboohr ai":           "https://bamboohr.com",
  "bardeen":               "https://bardeen.ai",
  "beacons":               "https://beacons.ai",
  "beacons ai":            "https://beacons.ai",
  "beatoven.ai":           "https://beatoven.ai",
  "beautiful.ai":          "https://beautiful.ai",
  "beehiiv":               "https://www.beehiiv.com/?via=benjie-gadiaza",
  "bill":                  "https://bill.com",
  "bill ai":               "https://bill.com",
  "bitboard":              "https://bitboard.co",
  "blackbox":              "https://blackbox.ai",
  "blackbox ai":           "https://blackbox.ai",
  "bland":                 "https://bland.ai",
  "bland ai":              "https://bland.ai",
  "bolt.new":              "https://bolt.new",
  "boomy":                 "https://boomy.com",
  "brainly":               "https://brainly.com",
  "brand24":               "https://brand24.com",
  "brand24 ai":            "https://brand24.com",
  "brandmark":             "https://brandmark.io",
  "brex":                  "https://brex.com",
  "brex ai":               "https://brex.com",
  "browse":                "https://browse.ai",
  "browse ai":             "https://browse.ai",
  "bubble":                "https://bubble.io",
  "bubble ai":             "https://bubble.io",
  "buffer":                "https://buffer.com",
  "buffer ai":             "https://buffer.com",
  "canva":                 "https://canva.com",
  "canva ai":              "https://canva.com/ai-image-generator",
  "canva ai video":        "https://canva.com/video",
  "capacities":            "https://capacities.io",
  "capcut":                "https://capcut.com",
  "capcut ai":             "https://capcut.com",
  "captions":              "https://captions.ai",
  "captions ai":           "https://captions.ai",
  "casetext":              "https://casetext.com",
  "casetext ai":           "https://casetext.com",
  "cerebras":              "https://cerebras.ai",
  "character.ai":          "https://character.ai",
  "chatgpt":               "https://chat.openai.com",
  "chili piper":           "https://chilipiper.com",
  "chili piper ai":        "https://chilipiper.com",
  "chorus":                "https://chorus.ai",
  "chorus ai":             "https://chorus.ai",
  "claude":                "https://claude.ai",
  "clay":                  "https://clay.com",
  "cleanvoice":            "https://cleanvoice.ai",
  "cleanvoice ai":         "https://cleanvoice.ai",
  "clearbit":              "https://clearbit.com",
  "clearbit ai":           "https://clearbit.com",
  "clearscope":            "https://clearscope.io",
  "clickup":               "https://clickup.com",
  "clickup ai":            "https://clickup.com",
  "clipdrop":              "https://clipdrop.co",
  "coda":                  "https://coda.io",
  "coda ai":               "https://coda.io",
  "codeium":               "https://codeium.com",
  "cohere":                "https://cohere.com",
  "colossyan":             "https://colossyan.com",
  "command center":        "https://commandcenter.dev",
  "conductor":             "https://conductor.com",
  "connected papers":      "https://connectedpapers.com",
  "consensus":             "https://consensus.app",
  "consensus ai":          "https://consensus.app",
  "content at scale":      "https://contentatscale.ai",
  "contentstudio":         "https://contentstudio.io",
  "contentstudio ai":      "https://contentstudio.io",
  "continue.dev":          "https://continue.dev",
  "convergence proxy":     "https://convergence.ai",
  "copilot studio":        "https://copilotstudio.microsoft.com",
  "copy.ai":               "https://copy.ai",
  "copysmith":             "https://copysmith.ai",
  "corti":                 "https://corti.ai",
  "corti ai":              "https://corti.ai",
  "coursera":              "https://coursera.org",
  "coursera ai":           "https://coursera.org",
  "craft":                 "https://craft.do",
  "craft ai":              "https://craft.do",
  "craiyon":               "https://craiyon.com",
  "crisp":                 "https://crisp.chat",
  "cursor":                "https://cursor.com",
  "d-id":                  "https://d-id.com",
  "dall-e 3":              "https://openai.com/dall-e-3",
  "databox":               "https://databox.com",
  "databox ai":            "https://databox.com",
  "deepbrain":             "https://deepbrain.io",
  "deepbrain ai":          "https://deepbrain.io",
  "deepgram":              "https://deepgram.com",
  "deepl":                 "https://deepl.com",
  "deepseek":              "https://chat.deepseek.com",
  "descript":              "https://descript.com",
  "descript ai":           "https://descript.com",
  "designs.ai":            "https://designs.ai",
  "devin":                 "https://cognition.ai",
  "devin ai":              "https://cognition.ai",
  "digits":                "https://digits.com",
  "domo":                  "https://domo.com",
  "domo ai":               "https://domo.com",
  "dovetail":              "https://dovetail.com",
  "dreamstudio":           "https://dreamstudio.ai",
  "drift":                 "https://drift.com",
  "drift ai":              "https://drift.com",
  "drip":                  "https://drip.com",
  "drip ai":               "https://drip.com",
  "dubverse":              "https://dubverse.ai",
  "duolingo max":          "https://duolingo.com",
  "durable":               "https://durable.co",
  "durable ai":            "https://durable.co",
  "eightfold":             "https://eightfold.ai",
  "eightfold ai":          "https://eightfold.ai",
  "elai.io":               "https://elai.io",
  "elevenlabs":            "https://try.elevenlabs.io/flxscqgtf1ys",
  "elicit":                "https://elicit.com",
  "elicit ai":             "https://elicit.com",
  "elpass":                "https://elpass.app",
  "elpass ai":             "https://elpass.app",
  "evisort":               "https://evisort.com",
  "evisort ai":            "https://evisort.com",
  "expensify":             "https://expensify.com",
  "explainpaper":          "https://explainpaper.com",
  "fal.ai":                "https://fal.ai",
  "fathom":                "https://fathom.video",
  "fathom ai":             "https://fathom.video",
  "feedhive":              "https://feedhive.com",
  "fetcher":               "https://fetcher.ai",
  "fetcher ai":            "https://fetcher.ai",
  "figma":                 "https://figma.com",
  "figma ai":              "https://figma.com",
  "fillout":               "https://fillout.com",
  "fillout ai":            "https://fillout.com",
  "fireflies.ai":          "https://fireflies.ai/?fpr=benjie21",
  "fireworks":             "https://fireworks.ai",
  "fireworks ai":          "https://fireworks.ai",
  "fliki":                 "https://fliki.ai",
  "flutterflow":           "https://flutterflow.io",
  "flutterflow ai":        "https://flutterflow.io",
  "flux":                  "https://blackforestlabs.ai",
  "flux ai":               "https://blackforestlabs.ai",
  "folk ai crm":           "https://folk.app",
  "forethought":           "https://forethought.ai",
  "forethought ai":        "https://forethought.ai",
  "formsort":              "https://formsort.com",
  "formsort ai":           "https://formsort.com",
  "fotor":                 "https://fotor.com",
  "fotor ai":              "https://fotor.com",
  "framer":                "https://framer.com",
  "framer ai":             "https://framer.com",
  "frase":                 "https://frase.io",
  "freepik":               "https://freepik.com/ai",
  "freepik ai":            "https://freepik.com/ai",
  "freshbooks":            "https://freshbooks.com",
  "freshbooks ai":         "https://freshbooks.com",
  "freshdesk":             "https://freshdesk.com",
  "freshdesk ai":          "https://freshdesk.com",
  "fullstory":             "https://fullstory.com",
  "fullstory ai":          "https://fullstory.com",
  "galileo":               "https://usegalileo.ai",
  "galileo ai":            "https://usegalileo.ai",
  "gamma":                 "https://gamma.app",
  "gemini":                "https://gemini.google.com",
  "getimg.ai":             "https://getimg.ai",
  "getresponse":           "https://getresponse.com",
  "getresponse ai":        "https://getresponse.com",
  "github copilot":        "https://github.com/features/copilot",
  "glean":                 "https://glean.com",
  "glean ai":              "https://glean.com",
  "glide":                 "https://glideapps.com",
  "glide ai":              "https://glideapps.com",
  "goldcast":              "https://goldcast.io",
  "gong":                  "https://gong.io",
  "gong ai":               "https://gong.io",
  "google ai studio":      "https://aistudio.google.com",
  "gorgias":               "https://gorgias.com",
  "gorgias ai":            "https://gorgias.com",
  "gpt engineer":          "https://gptengineer.app",
  "grammarly":             "https://grammarly.com",
  "granola":               "https://granola.ai",
  "greenhouse":            "https://greenhouse.io",
  "greenhouse ai":         "https://greenhouse.io",
  "grok":                  "https://grok.com",
  "groq":                  "https://groq.com",
  "growthbar seo":         "https://growthbarseo.com",
  "gumroad":               "https://gumroad.com",
  "gumroad ai":            "https://gumroad.com",
  "guru":                  "https://getguru.com",
  "guru ai":               "https://getguru.com",
  "hailuo":                "https://hailuoai.com",
  "hailuo ai":             "https://hailuoai.com",
  "haiper":                "https://haiper.ai",
  "haiper ai":             "https://haiper.ai",
  "happyfox":              "https://happyfox.com",
  "harvey":                "https://harvey.ai",
  "harvey ai":             "https://harvey.ai",
  "haystack":              "https://haystack.deepset.ai",
  "haystack ai":           "https://haystack.deepset.ai",
  "heap":                  "https://heap.io",
  "heap ai":               "https://heap.io",
  "heights platform":      "https://heightsplatform.com",
  "heights platform ai":   "https://heightsplatform.com",
  "helpshift":             "https://helpshift.com",
  "helpshift ai":          "https://helpshift.com",
  "hemingway editor":      "https://hemingwayapp.com",
  "heygen":                "https://heygen.com",
  "heygen ai":             "https://heygen.com",
  "hirevue":               "https://hirevue.com",
  "hootsuite":             "https://hootsuite.com",
  "hootsuite ai":          "https://hootsuite.com",
  "hotjar":                "https://hotjar.com",
  "hotjar ai":             "https://hotjar.com",
  "hubspot":               "https://hubspot.com",
  "hubspot ai":            "https://hubspot.com",
  "hubspot sales":         "https://hubspot.com/products/sales",
  "hubspot sales ai":      "https://hubspot.com/products/sales",
  "hugging face":          "https://huggingface.co",
  "hunter.io":             "https://hunter.io",
  "hypefury":              "https://hypefury.com",
  "hyper":                 "https://hyper.co",
  "hyperwrite":            "https://hyperwrite.ai",
  "hypotenuse":            "https://hypotenuse.ai",
  "hypotenuse ai":         "https://hypotenuse.ai",
  "ideogram":              "https://ideogram.ai",
  "ideogram ai":           "https://ideogram.ai",
  "ink":                   "https://inkforall.com",
  "ink ai":                "https://inkforall.com",
  "instantly":             "https://instantly.ai",
  "instantly ai":          "https://instantly.ai",
  "intercom":              "https://intercom.com",
  "intercom ai":           "https://intercom.com",
  "intuned":               "https://intuned.io",
  "invideo":               "https://invideo.io",
  "invideo ai":            "https://invideo.ai",
  "iris.ai":               "https://iris.ai",
  "ironclad":              "https://ironcladapp.com",
  "ironclad ai":           "https://ironcladapp.com",
  "jasper":                "https://jasper.ai",
  "jasper ai":             "https://jasper.ai",
  "jetbrains":             "https://jetbrains.com/ai",
  "jetbrains ai":          "https://jetbrains.com/ai",
  "journalist":            "https://journalist.ai",
  "journalist ai":         "https://journalist.ai",
  "junia":                 "https://junia.ai",
  "junia ai":              "https://junia.ai",
  "juro":                  "https://juro.com",
  "juro ai":               "https://juro.com",
  "kafkai":                "https://kafkai.com",
  "kajabi":                "https://kajabi.com",
  "kajabi ai":             "https://kajabi.com",
  "kensho":                "https://kensho.com",
  "keyword insights":      "https://www.keywordinsights.ai/?ref=myaitoolsfinder",
  "khan academy":          "https://khanacademy.org/khan-labs",
  "khan academy ai":       "https://khanacademy.org/khan-labs",
  "khroma":                "https://khroma.co",
  "kikubot":               "https://kikubot.com",
  "klap":                  "https://klap.app",
  "klarity":               "https://klaritylaw.com",
  "klarity ai":            "https://klaritylaw.com",
  "klaviyo":               "https://klaviyo.com",
  "klaviyo ai":            "https://klaviyo.com",
  "klaviyo email":         "https://klaviyo.com",
  "klenty":                "https://klenty.com",
  "klenty ai":             "https://klenty.com",
  "kleo":                  "https://kleo.so",
  "kleo ai":               "https://kleo.so",
  "kling":                 "https://klingai.com",
  "kling ai":              "https://klingai.com",
  "krea":                  "https://krea.ai",
  "krea ai":               "https://krea.ai",
  "krea canvas":           "https://krea.ai",
  "krisp":                 "https://krisp.ai",
  "kustomer":              "https://kustomer.com",
  "kustomer ai":           "https://kustomer.com",
  "lalal.ai":              "https://lalal.ai",
  "lambda labs":           "https://lambdalabs.com",
  "languagetool":          "https://languagetool.org",
  "lattice":               "https://lattice.com",
  "lattice ai":            "https://lattice.com",
  "lavender":              "https://lavender.ai",
  "laxis":                 "https://laxis.com",
  "laxis ai":              "https://laxis.com",
  "leapsome":              "https://leapsome.com",
  "leapsome ai":           "https://leapsome.com",
  "leena":                 "https://leena.ai",
  "leena ai":              "https://leena.ai",
  "lemlist":               "https://lemlist.com",
  "leonardo.ai":           "https://leonardo.ai",
  "lexica art":            "https://lexica.art",
  "limespot":              "https://limespot.io",
  "limespot ai":           "https://limespot.io",
  "lindy":                 "https://lindy.ai",
  "lindy ai":              "https://lindy.ai",
  "listnr":                "https://listnr.tech",
  "listnr ai":             "https://listnr.tech",
  "livechat":              "https://livechat.com",
  "livechat ai":           "https://livechat.com",
  "longshot":              "https://longshot.ai",
  "longshot ai":           "https://longshot.ai",
  "looka":                 "https://looka.com",
  "looker":                "https://looker.google.com",
  "looker ai":             "https://looker.google.com",
  "loom":                  "https://loom.com",
  "loom ai":               "https://loom.com",
  "loomly":                "https://loomly.com",
  "loomly ai":             "https://loomly.com",
  "lovable":               "https://lovable.dev",
  "lovo":                  "https://lovo.ai",
  "lovo ai":               "https://lovo.ai",
  "luma dream machine":    "https://lumalabs.ai/dream-machine",
  "lumalabs":              "https://lumalabs.ai",
  "lumalabs ai":           "https://lumalabs.ai",
  "lumen5":                "https://lumen5.com",
  "lumen5 ai":             "https://lumen5.com",
  "luminance":             "https://luminance.com",
  "luminar":               "https://skylum.com/luminar-ai",
  "luminar ai":            "https://skylum.com/luminar-ai",
  "luminar neo":           "https://skylum.com",
  "lusha":                 "https://lusha.com",
  "lusha ai":              "https://lusha.com",
  "magical":               "https://getmagical.com",
  "magnific":              "https://magnific.ai",
  "magnific ai":           "https://magnific.ai",
  "magnific upscale":      "https://magnific.ai",
  "mailchimp":             "https://mailchimp.com",
  "mailchimp ai":          "https://mailchimp.com",
  "mailerlite":            "https://mailerlite.com",
  "mailerlite ai":         "https://mailerlite.com",
  "make.com":              "https://www.make.com/en/register?pc=myaitoolsfinder",
  "manatal":               "https://manatal.com",
  "manatal ai":            "https://manatal.com",
  "marblism":              "https://marblism.com",
  "marketmuse":            "https://marketmuse.com",
  "mem":                   "https://mem.ai",
  "mem ai":                "https://mem.ai",
  "mem.ai":                "https://mem.ai",
  "memrise":               "https://memrise.com",
  "mention":               "https://mention.com",
  "mention ai":            "https://mention.com",
  "mercury":               "https://mercury.com",
  "mercury ai":            "https://mercury.com",
  "meshy":                 "https://meshy.ai",
  "meshy ai":              "https://meshy.ai",
  "meta":                  "https://meta.ai",
  "meta ai":               "https://meta.ai",
  "metricool":             "https://metricool.com",
  "metricool ai":          "https://metricool.com",
  "microsoft clarity":     "https://clarity.microsoft.com",
  "microsoft copilot":     "https://copilot.microsoft.com",
  "microsoft designer":    "https://designer.microsoft.com",
  "microsoft power automate": "https://powerautomate.microsoft.com",
  "midjourney":            "https://midjourney.com",
  "mintlify":              "https://mintlify.com",
  "miro":                  "https://miro.com/ai",
  "miro ai":               "https://miro.com/ai",
  "mistral":               "https://mistral.ai",
  "mistral ai":            "https://mistral.ai",
  "mixpanel":              "https://mixpanel.com",
  "modal":                 "https://modal.com",
  "monday.com":            "https://monday.com",
  "monday.com ai":         "https://monday.com",
  "monkeylearn":           "https://monkeylearn.com",
  "morgen":                "https://morgen.so",
  "motion":                "https://usemotion.com",
  "moz pro":               "https://moz.com",
  "moz pro ai":            "https://moz.com",
  "murf":                  "https://murf.ai",
  "murf ai":               "https://murf.ai",
  "mutableai":             "https://mutable.ai",
  "n8n":                   "https://n8n.io",
  "nabla copilot":         "https://nabla.com",
  "narrato":               "https://narrato.io",
  "navan":                 "https://navan.com",
  "navan ai":              "https://navan.com",
  "netomi":                "https://netomi.com",
  "netomi ai":             "https://netomi.com",
  "neuronwriter":          "https://app.neuronwriter.com/ar/a164b2cc978873dc1a98713284d9b87a",
  "neverinstall":          "https://neverinstall.com",
  "nightcafe":             "https://nightcafe.studio",
  "nightcafe ai":          "https://nightcafe.studio",
  "nomic":                 "https://nomic.ai",
  "nomic ai":              "https://nomic.ai",
  "notebooklm":            "https://notebooklm.google.com",
  "notion":                "https://notion.so/product/ai",
  "notion ai":             "https://notion.so/product/ai",
  "notion calendar":       "https://calendar.notion.so",
  "notta":                 "https://notta.ai",
  "notta ai":              "https://notta.ai",
  "nuance dax":            "https://nuance.com/healthcare",
  "obsidian":              "https://obsidian.md",
  "obsidian ai":           "https://obsidian.md",
  "obviously":             "https://obviously.ai",
  "obviously ai":          "https://obviously.ai",
  "ocoya":                 "https://ocoya.com",
  "ocoya ai":              "https://ocoya.com",
  "omnisend":              "https://omnisend.com",
  "omnisend ai":           "https://omnisend.com",
  "openrouter":            "https://openrouter.ai",
  "opusclip":              "https://www.opus.pro/?via=myaitoolsfinder",
  "otter.ai":              "https://otter.ai",
  "outranking":            "https://outranking.io",
  "outreach":              "https://outreach.io",
  "outreach ai":           "https://outreach.io",
  "outreach kaia":         "https://outreach.io/kaia",
  "pabbly connect":        "https://pabbly.com/connect",
  "pabbly connect ai":     "https://pabbly.com/connect",
  "pageoptimizer pro":     "https://pageoptimizer.pro",
  "pallyy":                "https://pallyy.com",
  "pallyy ai":             "https://pallyy.com",
  "paperpal":              "https://paperpal.com",
  "paradox":               "https://paradox.ai",
  "paradox ai":            "https://paradox.ai",
  "pencil":                "https://trypencil.com",
  "perplexity":            "https://perplexity.ai",
  "perplexity ai":         "https://perplexity.ai",
  "perplexity labs":       "https://perplexity.ai/labs",
  "phantombuster":         "https://phantombuster.com",
  "phind":                 "https://phind.com",
  "photomath":             "https://photomath.com",
  "photoroom":             "https://photoroom.com",
  "pi":                    "https://pi.ai",
  "picsart":               "https://picsart.com",
  "picsart ai":            "https://picsart.com",
  "pictory":               "https://pictory.ai",
  "pictory ai":            "https://pictory.ai",
  "picwish":               "https://picwish.com",
  "pieces for developers": "https://pieces.app",
  "pika labs":             "https://pika.art",
  "pinecone":              "https://pinecone.io",
  "pipedream":             "https://pipedream.com",
  "pipedrive":             "https://pipedrive.com",
  "pipedrive ai":          "https://pipedrive.com",
  "pitch":                 "https://pitch.com",
  "pixelcut":              "https://pixelcut.ai",
  "play.ht":               "https://play.ht",
  "playground":            "https://playground.com",
  "playground ai":         "https://playground.com",
  "podcastle":             "https://podcastle.ai",
  "podcastle ai":          "https://podcastle.ai",
  "podia":                 "https://podia.com",
  "podia ai":              "https://podia.com",
  "poe":                   "https://poe.com",
  "polymer":               "https://polymersearch.com",
  "power bi":              "https://powerbi.microsoft.com",
  "power bi ai":           "https://powerbi.microsoft.com",
  "predis.ai":             "https://predis.ai?ref=myaitoolsfinder",
  "privy":                 "https://privy.com",
  "privy ai":              "https://privy.com",
  "prowritingaid":         "https://prowritingaid.com",
  "publer":                "https://publer.com",
  "publer ai":             "https://publer.com",
  "qdrant":                "https://qdrant.tech",
  "qodo":                  "https://qodo.ai",
  "qualified":             "https://qualified.com",
  "qualified ai":          "https://qualified.com",
  "quickbooks":            "https://quickbooks.intuit.com",
  "quickbooks ai":         "https://quickbooks.intuit.com",
  "quillbot":              "https://quillbot.com",
  "quizlet":               "https://quizlet.com",
  "quizlet ai":            "https://quizlet.com",
  "ramp":                  "https://ramp.com",
  "ramp ai":               "https://ramp.com",
  "rankmath":              "https://rankmath.com/?ref=benjie-6423",
  "rankmath ai":           "https://rankmath.com/?ref=benjie-6423",
  "read":                  "https://read.ai",
  "read ai":               "https://read.ai",
  "rebuy":                 "https://rebuyengine.com",
  "rebuy ai":              "https://rebuyengine.com",
  "reclaim":               "https://go.reclaim.ai/do7hs1jez62m",
  "reclaim ai":            "https://go.reclaim.ai/do7hs1jez62m",
  "recraft":               "https://recraft.ai",
  "reflect":               "https://reflect.app",
  "reflect ai":            "https://reflect.app",
  "regie.ai":              "https://regie.ai",
  "relay.app":             "https://relay.app",
  "relume":                "https://relume.io",
  "relume ai":             "https://relume.io",
  "remove.bg":             "https://remove.bg",
  "rendernet":             "https://rendernet.ai",
  "rendernet ai":          "https://rendernet.ai",
  "replicate":             "https://replicate.com",
  "replika":               "https://replika.com",
  "replit":                "https://replit.com",
  "replit agent":          "https://replit.com/ai",
  "replit ai":             "https://replit.com",
  "reply.io":              "https://reply.io",
  "researchrabbit":        "https://researchrabbit.ai",
  "resemble":              "https://resemble.ai",
  "resemble ai":           "https://resemble.ai",
  "respell":               "https://respell.ai",
  "respell ai":            "https://respell.ai",
  "retool":                "https://retool.com",
  "retool ai":             "https://retool.com",
  "rippling":              "https://rippling.com",
  "rippling ai":           "https://rippling.com",
  "rive":                  "https://rive.app",
  "rive ai":               "https://rive.app",
  "riverside":             "https://riverside.fm",
  "riverside ai":          "https://riverside.fm",
  "routine":               "https://routine.co",
  "rows":                  "https://rows.com",
  "rows ai":               "https://rows.com",
  "runway":                "https://runwayml.com",
  "rytr":                  "https://rytr.me",
  "saga":                  "https://saga.so",
  "saga ai":               "https://saga.so",
  "salesforce einstein":   "https://salesforce.com/artificial-intelligence",
  "saleshandy":            "https://saleshandy.com",
  "saleshandy ai":         "https://saleshandy.com",
  "salesloft":             "https://salesloft.com",
  "salesloft ai":          "https://salesloft.com",
  "scenario":              "https://scenario.com",
  "scenario ai":           "https://scenario.com",
  "scholarcy":             "https://scholarcy.com",
  "scispace":              "https://scispace.com/?via=myaitoolsfinder",
  "scite":                 "https://scite.ai",
  "se ranking":            "https://seranking.com",
  "se ranking ai":         "https://seranking.com",
  "seaart":                "https://seaart.ai",
  "seaart ai":             "https://seaart.ai",
  "seamless.ai":           "https://seamless.ai",
  "seekout":               "https://seekout.io",
  "seekout ai":            "https://seekout.io",
  "segment":               "https://segment.com",
  "semantic scholar":      "https://semanticscholar.org",
  "semrush":               "https://semrush.com",
  "seo.ai":                "https://seo.ai",
  "seowind":               "https://seowind.io",
  "shopify magic":         "https://shopify.com/magic",
  "simplified":            "https://simplified.com?fpr=benjie19",
  "slidebean":             "https://slidebean.com",
  "slidesai":              "https://slidesai.io",
  "smartlead":             "https://smartlead.ai",
  "smartly.io":            "https://smartly.io",
  "smartsheet":            "https://smartsheet.com",
  "smartsheet ai":         "https://smartsheet.com",
  "smsbump":               "https://smsbump.com",
  "snov.io":               "https://snov.io",
  "socialbee":             "https://socialbee.com",
  "socialbee ai":          "https://socialbee.com",
  "socratic":              "https://socratic.org",
  "softr":                 "https://softr.io",
  "softr ai":              "https://softr.io",
  "sora":                  "https://sora.com",
  "soundful":              "https://soundful.com",
  "soundraw":              "https://soundraw.io/?ref=myaitoolsfinder",
  "sourcely":              "https://sourcely.net",
  "speechify":             "https://speechify.com",
  "speechmatics":          "https://speechmatics.com",
  "spellbook":             "https://spellbook.legal",
  "spellbook ai":          "https://spellbook.legal",
  "spline":                "https://spline.design",
  "spline ai":             "https://spline.design",
  "spyfu":                 "https://spyfu.com",
  "spyfu ai":              "https://spyfu.com",
  "stable diffusion":      "https://stability.ai",
  "stampli":               "https://stampli.com",
  "stampli ai":            "https://stampli.com",
  "stan":                  "https://stan.store",
  "stan ai":               "https://stan.store",
  "steve.ai":              "https://steve.ai",
  "storydoc":              "https://storydoc.com",
  "submagic":              "https://submagic.co",
  "submagic ai":           "https://submagic.co/?via=benjie11",
  "sudowrite":             "https://sudowrite.com",
  "suki":                  "https://suki.ai",
  "suki ai":               "https://suki.ai",
  "suno":                  "https://suno.com",
  "sunsama":               "https://sunsama.com",
  "supermaven":            "https://supermaven.com",
  "supermaven ai":         "https://supermaven.com",
  "supermetrics":          "https://supermetrics.com",
  "supermetrics ai":       "https://supermetrics.com",
  "surfer seo":            "https://surferseo.com",
  "swimm":                 "https://swimm.io",
  "synthesia":             "https://synthesia.io",
  "synthesis":             "https://synthesis.com",
  "tableau":               "https://tableau.com",
  "tableau ai":            "https://tableau.com",
  "tabnine":               "https://tabnine.com",
  "talkwalker":            "https://talkwalker.com",
  "talkwalker ai":         "https://talkwalker.com",
  "tally forms":           "https://tally.so",
  "tally forms ai":        "https://tally.so",
  "tana":                  "https://tana.inc",
  "tana ai":               "https://tana.inc",
  "tapcart":               "https://tapcart.com",
  "tapcart ai":            "https://tapcart.com",
  "taplio":                "https://taplio.com",
  "taskade":               "https://taskade.com",
  "taskade ai":            "https://www.taskade.com/?via=b3q5tf",
  "tavus":                 "https://tavus.io",
  "teachable":             "https://teachable.com",
  "teachable ai":          "https://teachable.com",
  "tettra":                "https://tettra.com",
  "tettra ai":             "https://tettra.com",
  "texta.ai":              "https://texta.ai",
  "textblaze":             "https://blaze.today",
  "thinkific":             "https://thinkific.com",
  "thinkific ai":          "https://thinkific.com",
  "tidio":                 "https://tidio.com",
  "tl;dv":                 "https://tldv.io",
  "tl;dv ai":              "https://tldv.io",
  "together":              "https://together.ai",
  "together ai":           "https://together.ai",
  "tome":                  "https://tome.app",
  "trainual":              "https://trainual.com",
  "trainual ai":           "https://trainual.com",
  "tray.ai":               "https://tray.ai",
  "tribescaler":           "https://tribescaler.com",
  "triple whale":          "https://triplewhale.com",
  "trullion":              "https://trullion.com",
  "trullion ai":           "https://trullion.com",
  "typeface":              "https://typeface.ai",
  "typeform":              "https://typeform.com",
  "typeform ai":           "https://typeform.com",
  "udio":                  "https://udio.com",
  "uizard":                "https://uizard.io",
  "undermind":             "https://undermind.ai",
  "v0 by vercel":          "https://v0.dev",
  "vapi":                  "https://vapi.ai",
  "vapi ai":               "https://vapi.ai",
  "veed.io":               "https://veed.io",
  "vidnoz":                "https://vidnoz.com",
  "vidnoz ai":             "https://vidnoz.com",
  "vidyo.ai":              "https://vidyo.ai",
  "visily":                "https://visily.ai",
  "visily ai":             "https://visily.ai",
  "visme":                 "https://visme.co",
  "visme ai":              "https://visme.co",
  "vista social":          "https://vistasocial.com",
  "vizard":                "https://vizard.ai",
  "vmaker":                "https://vmaker.com",
  "vmaker ai":             "https://vmaker.com",
  "voicemod":              "https://voicemod.net",
  "voicemod ai":           "https://voicemod.net",
  "voyage":                "https://voyageai.com",
  "voyage ai":             "https://voyageai.com",
  "weaviate":              "https://weaviate.io",
  "wellsaid labs":         "https://wellsaidlabs.com",
  "weweb":                 "https://weweb.io",
  "weweb ai":              "https://weweb.io",
  "whimsical":             "https://whimsical.com",
  "whimsical ai":          "https://whimsical.com",
  "windsurf":              "https://codeium.com/windsurf",
  "wisecut":               "https://wisecut.video",
  "wispr flow":            "https://wispr.ai",
  "wix":                   "https://wix.com/ai-website-builder",
  "wix ai":                "https://wix.com/ai-website-builder",
  "wolfram alpha":         "https://wolframalpha.com",
  "wombo dream":           "https://dream.ai",
  "woodpecker":            "https://woodpecker.co",
  "woodpecker ai":         "https://woodpecker.co",
  "wordtune":              "https://wordtune.com",
  "wordware":              "https://wordware.ai",
  "workato":               "https://workato.com",
  "workday":               "https://workday.com",
  "workday ai":            "https://workday.com",
  "writecream":            "https://writecream.com",
  "writer":                "https://writer.com",
  "writerzen":             "https://writerzen.net",
  "writesonic":            "https://writesonic.com?fp_ref=myaitoolsfinder",
  "xano":                  "https://xano.com",
  "xano ai":               "https://xano.com",
  "xembly":                "https://xembly.com",
  "yotpo":                 "https://yotpo.com",
  "yotpo ai":              "https://yotpo.com",
  "you.com":               "https://you.com",
  "yuma":                  "https://yuma.ai",
  "yuma ai":               "https://yuma.ai",
  "zapier":                "https://zapier.com",
  "zapier ai":             "https://zapier.com/ai",
  "zendesk":               "https://zendesk.com",
  "zendesk ai":            "https://zendesk.com",
  "zoho zia":              "https://zoho.com/crm/ai-sales-assistant.html",
  "zoominfo":              "https://zoominfo.com",
  "zoominfo ai":           "https://zoominfo.com",
  "zubtitle":              "https://zubtitle.com",
  "viggle": "https://viggle.ai",
  "elevenlabs reader": "https://reader.elevenlabs.io",
  "afforai": "https://afforai.com",
  "napkin ai": "https://napkin.ai",
  "turboscribe": "https://turboscribe.ai",
  "hix ai": "https://hix.ai",
  "elevenlabs dubbing": "https://elevenlabs.io/dubbing",
  "gumloop": "https://gumloop.com",
  "manufact": "https://manufact.dev",
  "outlier ai": "https://outlier.ai",
  "agnost ai": "https://agnost.ai",
  "traceforce": "https://traceforce.ai",
  "trickle ai": "https://trickle.so",
  "genspark": "https://genspark.ai",
  "bloomy": "https://bloomy.ai",
  "cohere coral": "https://coral.cohere.com",
  "palmier pro": "https://palmier.pro",
  "screenpipe": "https://screenpipe.com",
  "unlayer": "https://unlayer.com",
  "langy": "https://langy.ai",
  "sixb": "https://sixb.ai",
  "metaview": "https://metaview.ai",
  "langtrace": "https://langtrace.ai",
  "typeframes": "https://typeframes.com",
  "hyperprobe": "https://hyperprobe.dev",
  "hirenewtalent": "https://hirenewtalent.ai",
  "outset": "https://outset.ai",
  "agentevals": "https://agentevals.io",
  "discovered materials": "https://discoveredmaterials.com",
  "jobscan ai": "https://jobscan.co",
  "vendo": "https://vendo.dev",
  "onecli": "https://onecli.dev",
  "camel agi": "https://camelagi.com"
};
