/**
 * tools-data.js — MyAI ToolsFinder
 * Auto-generated. Do not edit manually.
 */
window.MYAI_AFF_MAP = {
  "activepieces":          "https://activepieces.com",
  "adcreative.ai":         "https://adcreative.ai",
  "adobe express":         "https://adobe.com/express",
  "adobe express ai":      "https://adobe.com/express",
  "adobe firefly":         "https://firefly.adobe.com",
  "adobe podcast":         "https://podcast.adobe.com",
  "ahrefs":                "https://ahrefs.com",
  "ai writer":             "https://ai-writer.com",
  "akkio":                 "https://akkio.com",
  "alphasense":            "https://alpha-sense.com",
  "amplitude":             "https://amplitude.com",
  "amplitude ai":          "https://amplitude.com",
  "anyword":               "https://anyword.com",
  "apollo.io":             "https://apollo.io",
  "askcodi":               "https://askcodi.com",
  "aws codewhisperer":     "https://aws.amazon.com/codewhisperer",
  "bardeen":               "https://bardeen.ai",
  "beatoven.ai":           "https://beatoven.ai",
  "beautiful.ai":          "https://beautiful.ai",
  "beehiiv":               "https://beehiiv.com",
  "blackbox":              "https://blackbox.ai",
  "blackbox ai":           "https://blackbox.ai",
  "bolt.new":              "https://bolt.new",
  "brainly":               "https://brainly.com",
  "brandmark":             "https://brandmark.io",
  "buffer":                "https://buffer.com",
  "buffer ai":             "https://buffer.com",
  "canva":                 "https://canva.com",
  "canva ai":              "https://canva.com/ai-image-generator",
  "capacities":            "https://capacities.io",
  "capcut":                "https://capcut.com",
  "capcut ai":             "https://capcut.com",
  "captions":              "https://captions.ai",
  "captions ai":           "https://captions.ai",
  "character.ai":          "https://character.ai",
  "chatgpt":               "https://chat.openai.com",
  "claude":                "https://claude.ai",
  "clay":                  "https://clay.com",
  "clearscope":            "https://clearscope.io",
  "clipdrop":              "https://clipdrop.co",
  "codeium":               "https://codeium.com",
  "cohere":                "https://cohere.com",
  "connected papers":      "https://connectedpapers.com",
  "consensus":             "https://consensus.app",
  "content at scale":      "https://contentatscale.ai",
  "continue.dev":          "https://continue.dev",
  "copy.ai":               "https://copy.ai",
  "coursera":              "https://coursera.org",
  "coursera ai":           "https://coursera.org",
  "craft":                 "https://craft.do",
  "craft ai":              "https://craft.do",
  "crisp":                 "https://crisp.chat",
  "cursor":                "https://cursor.com",
  "dall-e 3":              "https://openai.com/dall-e-3",
  "deepl":                 "https://deepl.com",
  "deepseek":              "https://chat.deepseek.com",
  "descript":              "https://descript.com",
  "designs.ai":            "https://designs.ai",
  "devin":                 "https://cognition.ai",
  "devin ai":              "https://cognition.ai",
  "digits":                "https://digits.com",
  "domo":                  "https://domo.com",
  "domo ai":               "https://domo.com",
  "duolingo max":          "https://duolingo.com",
  "durable":               "https://durable.co",
  "durable ai":            "https://durable.co",
  "eightfold":             "https://eightfold.ai",
  "eightfold ai":          "https://eightfold.ai",
  "elevenlabs":            "https://elevenlabs.io",
  "elicit":                "https://elicit.com",
  "expensify":             "https://expensify.com",
  "explainpaper":          "https://explainpaper.com",
  "figma":                 "https://figma.com",
  "figma ai":              "https://figma.com",
  "fireflies.ai":          "https://fireflies.ai",
  "fliki":                 "https://fliki.ai",
  "flux":                  "https://blackforestlabs.ai",
  "flux ai":               "https://blackforestlabs.ai",
  "framer":                "https://framer.com",
  "framer ai":             "https://framer.com",
  "frase":                 "https://frase.io",
  "freshdesk":             "https://freshdesk.com",
  "freshdesk ai":          "https://freshdesk.com",
  "gamma":                 "https://gamma.app",
  "gemini":                "https://gemini.google.com",
  "github copilot":        "https://github.com/features/copilot",
  "gong":                  "https://gong.io",
  "gong ai":               "https://gong.io",
  "grammarly":             "https://grammarly.com",
  "granola":               "https://granola.ai",
  "grok":                  "https://grok.com",
  "groq":                  "https://groq.com",
  "happyfox":              "https://happyfox.com",
  "hemingway editor":      "https://hemingwayapp.com",
  "heygen":                "https://heygen.com",
  "hirevue":               "https://hirevue.com",
  "hootsuite":             "https://hootsuite.com",
  "hootsuite ai":          "https://hootsuite.com",
  "hubspot":               "https://hubspot.com",
  "hubspot ai":            "https://hubspot.com",
  "hubspot sales":         "https://hubspot.com/products/sales",
  "hubspot sales ai":      "https://hubspot.com/products/sales",
  "hugging face":          "https://huggingface.co",
  "hyperwrite":            "https://hyperwrite.ai",
  "ideogram":              "https://ideogram.ai",
  "instantly":             "https://instantly.ai",
  "instantly ai":          "https://instantly.ai",
  "intercom":              "https://intercom.com",
  "intercom ai":           "https://intercom.com",
  "invideo":               "https://invideo.io",
  "invideo ai":            "https://invideo.io",
  "iris.ai":               "https://iris.ai",
  "jasper":                "https://jasper.ai",
  "jasper ai":             "https://jasper.ai",
  "kensho":                "https://kensho.com",
  "keyword insights":      "https://keywordinsights.ai",
  "khan academy":          "https://khanacademy.org/khan-labs",
  "khan academy ai":       "https://khanacademy.org/khan-labs",
  "khroma":                "https://khroma.co",
  "klaviyo":               "https://klaviyo.com",
  "klaviyo ai":            "https://klaviyo.com",
  "kling":                 "https://klingai.com",
  "kling ai":              "https://klingai.com",
  "krea":                  "https://krea.ai",
  "krea ai":               "https://krea.ai",
  "krisp":                 "https://krisp.ai",
  "lalal.ai":              "https://lalal.ai",
  "lavender":              "https://lavender.ai",
  "leena":                 "https://leena.ai",
  "leena ai":              "https://leena.ai",
  "lemlist":               "https://lemlist.com",
  "leonardo.ai":           "https://leonardo.ai",
  "longshot":              "https://longshot.ai",
  "longshot ai":           "https://longshot.ai",
  "looka":                 "https://looka.com",
  "lovable":               "https://lovable.dev",
  "lumen5":                "https://lumen5.com",
  "luminar neo":           "https://skylum.com",
  "magical":               "https://getmagical.com",
  "magnific":              "https://magnific.ai",
  "magnific ai":           "https://magnific.ai",
  "mailchimp":             "https://mailchimp.com",
  "mailchimp ai":          "https://mailchimp.com",
  "make.com":              "https://make.com",
  "marketmuse":            "https://marketmuse.com",
  "mem.ai":                "https://mem.ai",
  "memrise":               "https://memrise.com",
  "meta":                  "https://meta.ai",
  "meta ai":               "https://meta.ai",
  "microsoft copilot":     "https://copilot.microsoft.com",
  "microsoft power automate": "https://powerautomate.microsoft.com",
  "midjourney":            "https://midjourney.com",
  "mistral":               "https://mistral.ai",
  "mistral ai":            "https://mistral.ai",
  "mixpanel":              "https://mixpanel.com",
  "monkeylearn":           "https://monkeylearn.com",
  "morgen":                "https://morgen.so",
  "motion":                "https://usemotion.com",
  "murf":                  "https://murf.ai",
  "murf ai":               "https://murf.ai",
  "n8n":                   "https://n8n.io",
  "neuronwriter":          "https://neuronwriter.com",
  "nightcafe":             "https://nightcafe.studio",
  "notebooklm":            "https://notebooklm.google.com",
  "notion":                "https://notion.so/product/ai",
  "notion ai":             "https://notion.so/product/ai",
  "obsidian":              "https://obsidian.md",
  "obsidian ai":           "https://obsidian.md",
  "obviously":             "https://obviously.ai",
  "obviously ai":          "https://obviously.ai",
  "opusclip":              "https://opus.pro",
  "otter.ai":              "https://otter.ai",
  "outranking":            "https://outranking.io",
  "outreach":              "https://outreach.io",
  "outreach ai":           "https://outreach.io",
  "pabbly connect":        "https://pabbly.com/connect",
  "pageoptimizer pro":     "https://pageoptimizer.pro",
  "paradox":               "https://paradox.ai",
  "paradox ai":            "https://paradox.ai",
  "pencil":                "https://trypencil.com",
  "perplexity":            "https://perplexity.ai",
  "perplexity ai":         "https://perplexity.ai",
  "phantombuster":         "https://phantombuster.com",
  "phind":                 "https://phind.com",
  "photomath":             "https://photomath.com",
  "pi":                    "https://pi.ai",
  "pictory":               "https://pictory.ai",
  "picwish":               "https://picwish.com",
  "pieces for developers": "https://pieces.app",
  "pika labs":             "https://pika.art",
  "pipedream":             "https://pipedream.com",
  "pipedrive":             "https://pipedrive.com",
  "pipedrive ai":          "https://pipedrive.com",
  "pitch":                 "https://pitch.com",
  "play.ht":               "https://play.ht",
  "playground":            "https://playground.com",
  "playground ai":         "https://playground.com",
  "podcastle":             "https://podcastle.ai",
  "poe":                   "https://poe.com",
  "polymer":               "https://polymersearch.com",
  "predis.ai":             "https://predis.ai",
  "prowritingaid":         "https://prowritingaid.com",
  "quillbot":              "https://quillbot.com",
  "quizlet":               "https://quizlet.com",
  "quizlet ai":            "https://quizlet.com",
  "rankmath":              "https://rankmath.com",
  "rankmath ai":           "https://rankmath.com",
  "reclaim":               "https://reclaim.ai",
  "reclaim ai":            "https://reclaim.ai",
  "reflect":               "https://reflect.app",
  "relume":                "https://relume.io",
  "relume ai":             "https://relume.io",
  "remove.bg":             "https://remove.bg",
  "replicate":             "https://replicate.com",
  "replit":                "https://replit.com",
  "replit ai":             "https://replit.com",
  "researchrabbit":        "https://researchrabbit.ai",
  "resemble":              "https://resemble.ai",
  "resemble ai":           "https://resemble.ai",
  "routine":               "https://routine.co",
  "runway":                "https://runwayml.com",
  "rytr":                  "https://rytr.me",
  "salesforce einstein":   "https://salesforce.com/artificial-intelligence",
  "salesloft":             "https://salesloft.com",
  "scholarcy":             "https://scholarcy.com",
  "scispace":              "https://typeset.io",
  "scite":                 "https://scite.ai",
  "segment":               "https://segment.com",
  "semantic scholar":      "https://semanticscholar.org",
  "semrush":               "https://semrush.com",
  "seo.ai":                "https://seo.ai",
  "simplified":            "https://simplified.com",
  "slidebean":             "https://slidebean.com",
  "slidesai":              "https://slidesai.io",
  "socratic":              "https://socratic.org",
  "soundraw":              "https://soundraw.io",
  "speechify":             "https://speechify.com",
  "stable diffusion":      "https://stability.ai",
  "storydoc":              "https://storydoc.com",
  "submagic":              "https://submagic.co",
  "sudowrite":             "https://sudowrite.com",
  "suno":                  "https://suno.com",
  "sunsama":               "https://sunsama.com",
  "supermaven":            "https://supermaven.com",
  "surfer seo":            "https://surferseo.com",
  "synthesia":             "https://synthesia.io",
  "synthesis":             "https://synthesis.com",
  "tableau":               "https://tableau.com",
  "tableau ai":            "https://tableau.com",
  "tabnine":               "https://tabnine.com",
  "tana":                  "https://tana.inc",
  "taplio":                "https://taplio.com",
  "taskade":               "https://taskade.com",
  "tidio":                 "https://tidio.com",
  "together":              "https://together.ai",
  "together ai":           "https://together.ai",
  "tome":                  "https://tome.app",
  "tray.ai":               "https://tray.ai",
  "typeface":              "https://typeface.ai",
  "typeform":              "https://typeform.com",
  "typeform ai":           "https://typeform.com",
  "udio":                  "https://udio.com",
  "uizard":                "https://uizard.io",
  "v0 by vercel":          "https://v0.dev",
  "veed.io":               "https://veed.io",
  "visme":                 "https://visme.co",
  "visme ai":              "https://visme.co",
  "vizard":                "https://vizard.ai",
  "windsurf":              "https://codeium.com/windsurf",
  "wisecut":               "https://wisecut.video",
  "wix":                   "https://wix.com/ai-website-builder",
  "wix ai":                "https://wix.com/ai-website-builder",
  "wolfram alpha":         "https://wolframalpha.com",
  "wordtune":              "https://wordtune.com",
  "workato":               "https://workato.com",
  "workday":               "https://workday.com",
  "workday ai":            "https://workday.com",
  "writerzen":             "https://writerzen.net",
  "writesonic":            "https://writesonic.com",
  "xembly":                "https://xembly.com",
  "zapier":                "https://zapier.com",
  "zendesk":               "https://zendesk.com",
  "zendesk ai":            "https://zendesk.com",
  "luma dream machine": "https://lumalabs.ai/dream-machine",
  "recraft": "https://recraft.ai",
  "wordware": "https://wordware.ai",
  "fal.ai": "https://fal.ai"
};
